define(['handlebars.runtime'], function(Handlebars) {
  Handlebars = Handlebars["default"];  var template = Handlebars.template, templates = Handlebars.templates = Handlebars.templates || {};
templates['footer'] = template({"compiler":[5,">= 2.0.0"],"main":function(depth0,helpers,partials,data) {
  return "<!--\nTo change this template, choose Tools | Templates\nand open the template in the editor.\n-->\n<!DOCTYPE html>\n<html>\n    <head>\n        <title></title>\n        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n    </head>\n    <body>\n        <div>TODO write content</div>\n    </body>\n</html>\n";
  },"useData":true});
templates['header'] = template({"compiler":[5,">= 2.0.0"],"main":function(depth0,helpers,partials,data) {
  return "<div class=\"navbar navbar-default navbar-fixed-top\" role=\"navigation\">\n    <div class=\"container\">\n        <div class=\"navbar-header\">\n            <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">\n                <span class=\"sr-only\">Toggle navigation</span>\n                <span class=\"icon-bar\"></span>\n                <span class=\"icon-bar\"></span>\n                <span class=\"icon-bar\"></span>\n            </button>\n            <a class=\"navbar-brand\" href=\"#\">Gavin Wu's Baby Girl</a>\n        </div>\n        <div class=\"navbar-collapse collapse\">\n            <ul class=\"nav navbar-nav\">\n                <li menu-id=\"home\"><a href=\"#/home\">Home</a></li>\n                <li menu-id=\"about\"><a href=\"#/about\">About</a></li>\n                <li menu-id=\"contact\"><a href=\"#/contact\">Contact</a></li>\n                <!-- <li class=\"dropdown\">\n                    <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Dropdown <b class=\"caret\"></b></a>\n                    <ul class=\"dropdown-menu\">\n                        <li><a href=\"#\">Action</a></li>\n                        <li><a href=\"#\">Another action</a></li>\n                        <li><a href=\"#\">Something else here</a></li>\n                        <li class=\"divider\"></li>\n                        <li class=\"dropdown-header\">Nav header</li>\n                        <li><a href=\"#\">Separated link</a></li>\n                        <li><a href=\"#\">One more separated link</a></li>\n                    </ul>\n                </li> -->\n            </ul>\n            <!--<ul class=\"nav navbar-nav navbar-right\">\n                <li><a href=\"#\">Link</a></li>\n                <li><a href=\"#\">Link</a></li>\n                <li><a href=\"#\">Link</a></li>\n            </ul> -->\n        </div><!--/.nav-collapse -->\n    </div>\n</div>";
  },"useData":true});
return templates;
});